/*
 * Ork: a small object-oriented OpenGL Rendering Kernel.
 * Copyright (c) 2008-2010 INRIA
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or (at
 * your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA.
 */

/*
 * Authors: Eric Bruneton, Antoine Begault, Guillaume Piolat.
 */

#ifndef _ORK_COMPILED_RESOURCE_LOADER_H_
#define _ORK_COMPILED_RESOURCE_LOADER_H_

#include <map>

#include "ork/resource/ResourceLoader.h"

namespace ork
{

/**
 * A ResourceLoader that can load resources from the files produced by a
 * ResourceCompiler. This class is intended to be subclassed in order to
 * include the source code generated by a ResourceCompiler:
 \code
class MyResourceLoader : public CompiledResourceLoader
{
public:
    MyResourceLoader(const string &resourceDataFile) :
        CompiledResourceLoader(resourceDataFile)
    {
#include "resourceFile"
    }
};
\endcode
 * This source code will construct the %resource descriptors of the
 * resources that will be loaded by this loader, during the creation of
 * this loader.
 *
 * @ingroup resource
 */
class CompiledResourceLoader : public ResourceLoader
{
public:
    /*
     * A ResourceDescriptor that never delete its data part.
     */
    class StaticResourceDescriptor : public ResourceDescriptor
    {
    public:
        /**
         * Creates a new StaticResourceDescriptor.
         *
         * @param descriptor the XML part of this %resource descriptor.
         * @param data the ASCII of binary data part of the descriptor.
         * @param size the size of the ASCII or binary part in bytes.
         */
        StaticResourceDescriptor(const TiXmlElement *descriptor, unsigned char *data, unsigned int size);

        /**
         * Deletes this StaticResourceDescriptor.
         */
        virtual ~StaticResourceDescriptor();

        /**
         * Does nothing, i.e., do not delete the data of this descriptor.
         */
        virtual void clearData();
    };

    /**
     * Creates a new CompiledResourceLoader.
     *
     * @param resourceDataFile a file containing the data parts of the
     *      resources that must be loaded by this loader. This file
     *      must have been produced by a ResourceCompiler.
     */
    CompiledResourceLoader(const string &resourceDataFile);

    /**
     * Deletes this CompiledResourceLoader.
     */
    virtual ~CompiledResourceLoader();

    /**
     * Returns the path of the resource of the given name. This method
     * looks for paths stored in the #paths map, initialized during the
     * construction of this loader.
     *
     * @param name the name of a resource.
     * @return the path of this resource.
     * @throw exception if the resource is not found.
     */
    virtual string findResource(const string &name);

    /**
     * Loads the ResourceDescriptor of the given name. This method looks for
     * %resource descriptors stored in the #resources map, initialized
     * during the construction of this loader.
     *
     * @param name the name of the ResourceDescriptor to be loaded.
     * @return the ResourceDescriptor of the given name, or NULL if the %resource
     *      is not found.
     */
    virtual ptr<ResourceDescriptor> loadResource(const string &name);

    /**
     * Reloads the ResourceDescriptor of the given name. This method always
     * return NULL as the resources managed by this loader can not change.
     *
     * @param name the name of the ResourceDescriptor to be loaded.
     * @param currentValue the current value of this ResourceDescriptor.
     * @return the new value of this ResourceDescriptor, or NULL if this value
     *      has not changed.
     */
    virtual ptr<ResourceDescriptor> reloadResource(const string &name, ptr<ResourceDescriptor> currentValue);

protected:
    /**
     * The data parts of the resources that can be loaded by this loader.
     */
    unsigned char* data;

    /**
     * The paths that can be returned by #findResource.
     */
    map<string, string> paths;

    /**
     * The %resource descriptors that can be returned by #loadResource.
     */
    map< string, ptr<ResourceDescriptor> > resources;

    /**
     * Adds a %resource path to #paths. This method is called by the code
     * generated by ResourceCompiler.
     */
    void addPath(const string &name, const string &path);

    /**
     * Adds a %resource descriptor to #resources. This method is called by
     * the code generated by ResourceCompiler.
     */
    void addResource(const string &name, ptr<ResourceDescriptor> desc);
};

}

#endif
